### ISSUE TITLE
Project status Jun 2019

### ISSUE THREAD

**Issue by stacksmith** [Ferada/cl-cffi-gtk#30]
@Ferada - are you still active here?  I haven't checked in a while, and there is activity at the original repo.  I know you've made a lot of fixes - are they merged upstream?  Thanks

**Comment by Ferada** [comment]
Sure, just for work though.

That said, the original repo now has an enormous amount of changes from early this year and I'm not working on getting any fixes in this repo merged upstream due to lack of any response. So, from my side it's kind of a dead end.

**Comment by stacksmith** [comment]
Hmm.  Maybe @crategus doesn't like you for some reason.

**Comment by Ferada** [comment]
Maybe, maybe not. I can't justify spending time solving that problem at the moment.

Edit: It's `215 commits ahead, 452 commits behind` the source repo. And those aren't (for the biggest part) reformatting changes. It would take a lot of time making that compatible.

**Comment by stacksmith** [comment]
Sorry to add to your wasted time.  I am just trying to figure out which branch to use...  I know you've put in a lot of effort, and the last time I used cl-cffi-gtk there were some gaping holes..

**Comment by Ferada** [comment]
> Sorry to add to your wasted time.

No worries about that, it'll help other people asking the same question :)

> I am just trying to figure out which branch to use... I know you've put in a lot of effort, and the last time I used cl-cffi-gtk there were some gaping holes..

If you're not too bothered by the unmerged fixes probably best to follow crategus' repo since it looks to me like he'll follow the changes upcoming to GTK 4 too. Any kind of big changes (aka generated code / comments) is definitely better over there.

If you are ... well, if you could also make tickets for specific issues I can probably help out with patching those holes.

**Comment by stacksmith** [comment]
That was my thinking...  I appreciate your generous offer.  Thank you.
